version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: aegisguard_db
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
      POSTGRES_DB: aegisguard
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis -d aegisguard"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  backend:
    image: mlepnos/aegisguard-backend:1.0
    container_name: aegisguard_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: Host=db;Port=5432;Database=aegisguard;Username=aegis;Password=aegis
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports: ["5080:8080"]
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  frontend:
    image: mlepnos/aegisguard-frontend:1.0
    container_name: aegisguard_frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5270
      ASPNETCORE_ENVIRONMENT: Production
      ApiBaseUrl: http://backend:8080   # ← your Program.cs reads this
    ports:
      - "5270:5270"

volumes:
  db_data:
